[HLS-2323] undertow headers and HTTP base additions
helios/opentelemetry-java-instrumentation pull request #14
Opened 2022-08-04 10:11 UTC by levyoren

2022-08-05 13:38 UTC, nozik requested changes

2022-08-05 13:38 UTC, nozik commented on instrumentation/undertow-1.4/javaagent/src/test/groovy/UndertowServerTest.groovy
> +            "http.request.headers" { it != null }
Can't we parse "it" and see that what's there makes sense?

2022-08-05 13:38 UTC, nozik commented on instrumentation/undertow-1.4/javaagent/src/test/groovy/UndertowServerTest.groovy
> +            "http.request.headers" { it != null }
Same here + use the static consts of the attr name

2022-08-09 12:13 UTC, LironKS approved these changes

2022-08-09 12:30 UTC, nozik approved these changes

2022-08-09 12:30 UTC, merged