[HLS-2615] Fixes to instrumentation indication
helios/opentelemetry-java-instrumentation pull request #79
Opened 2022-12-19 16:27 UTC by YochayCO

2022-12-28 16:48 UTC, levyoren requested changes

2022-12-28 16:48 UTC, levyoren commented on instrumentation/log4j/log4j-appender-2.17/library/src/main/java/io/opentelemetry/instrumentation/log4j/appender/v2_17/internal/LogEventMapper.java
> +    attributes.put(HELIOS_INSTRUMENTED_INDICATION, "log4j");
don't we want to distinguish the two instrumentation? and set this to `log4j2`?

2022-12-28 16:48 UTC, levyoren commented on instrumentation/logback/logback-mdc-1.0/library/src/main/java/io/opentelemetry/instrumentation/logback/v1_0/LoggingEventWrapper.java
> +    System.out.println("help");
hope you're ok now :)
please remove.

2022-12-29 14:43 UTC, YochayCO commented on instrumentation/logback/logback-mdc-1.0/library/src/main/java/io/opentelemetry/instrumentation/logback/v1_0/LoggingEventWrapper.java
> +    System.out.println("help");
Yes it was rough 😆

2022-12-29 14:51 UTC, levyoren approved these changes

2022-12-29 15:38 UTC, YochayCO commented
@levyoren if only the muzzle fails we can merge this. ok?

2023-01-02 12:24 UTC, merged